#!/usr/bin/env bash
DIR=${PWD##*/}
echo "Current Location:" $DIR
if [ ! -d "/tmp/${PWD##*/}" ]; then
	mkdir /tmp/${PWD##*/}
else 
	rm -rf /tmp/${PWD##*/}
	mkdir /tmp/${PWD##*/}
fi
git clone --local . /tmp/$DIR/$(git describe --always)
~/hooks/check.sh "/tmp/$DIR/$(git describe --always)" "$PWD" 
